# Generated by Django 5.1.1 on 2024-11-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('direccion', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('fono', models.CharField(blank=True, max_length=20, null=True)),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='locales/')),
                ('valoraciones', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
    ]
