# Generated by Django 5.1.1 on 2024-11-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='locales/'),
        ),
    ]
