# Generated by Django 5.1.1 on 2024-11-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_local_valoraciones_alter_local_fono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
    ]
