# Generated by Django 5.1.1 on 2024-11-21 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='dueño',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='locales', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='local',
            name='imagen',
            field=models.ImageField(default=3, upload_to='locales/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='imagenes',
            field=models.ManyToManyField(blank=True, related_name='locales', to='core.imagen'),
        ),
    ]
