# Generated by Django 5.1.1 on 2024-12-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_valoracion_usuario_alter_valoracion_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='categoria',
            field=models.CharField(choices=[('NATURAL', 'Lugares Naturales'), ('CULTURAL', 'Patrimonio Cultural'), ('AVENTURA', 'Turismo de Aventura'), ('BIENESTAR', 'Lugares de Bienestar'), ('MISTERIOSO', 'Lugares Misteriosos'), ('COMUNITARIO', 'Turismo Social y Comunitario')], max_length=50),
        ),
    ]
