# Generated by Django 5.1.1 on 2024-12-19 00:46

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_local_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='fono',
        ),
        migrations.RemoveField(
            model_name='local',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='local',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.validate_telefono]),
        ),
        migrations.AddField(
            model_name='local',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
