# Generated by Django 5.1.1 on 2024-12-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_local_fono_remove_local_imagenes_local_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='categoria',
            field=models.CharField(choices=[('Turismo', 'Turismo'), ('Restaurante', 'Restaurante'), ('Hospedaje', 'Hospedaje'), ('Aventura', 'Turismo de Aventura'), ('Natural', 'Lugar Natural'), ('Cultural', 'Patrimonio Cultural')], max_length=50),
        ),
    ]
