# Generated by Django 5.1.1 on 2024-12-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_local_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(choices=[('Error/Bug', 'Error/Bug'), ('Mejora', 'Mejora'), ('Sugerencia', 'Nueva Funcionalidad')], max_length=50)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Madia'), ('Alta', 'Alta')], max_length=50)),
                ('captura', models.ImageField(upload_to='bugimagenes/')),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
